import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { UILibraryEntry, Helper } from "./common.slint";
import { Theme } from "./theme.slint";
import { TileListView } from "./tile_list_view.slint";
import { DetailListView } from "detail_list_view.slint";

export global Content {
    in property <string> variant: "spotify";
    in property <[[UILibraryEntry]]> tile-rows: [[{id: 0, parent_id: 0, variant: "folder", name: "test", played_at: "", image: [], sort_key: 0}]];
    in property <[UILibraryEntry]> detail-rows: [{id: 0, parent_id: 0, variant: "folder", name: "test", played_at: "", image: [], sort_key: 0}];
    callback select-library-entry(int /* id */);
}

export component ContentView {
    height: 100%;
    width: 100%;

    if Content.variant == "folder" || Content.variant == "stream":
        TileListView {
            rows: Content.tile-rows;
            entry-clicked(id) => {
                Content.select-library-entry(id);
            }
        }
    if Content.variant != "folder" && Content.variant != "stream":
        DetailListView {
            rows: Content.detail-rows;
            entry-clicked(id) => {
                Content.select-library-entry(id);
            }
        }
}
