import { VerticalBox, HorizontalBox, ScrollView } from "std-widgets.slint";
import { Theme } from "./theme.slint";
import { UILibraryEntry, Helper } from "./common.slint";

export component Tile {
    in property <int> id;
    in property <int> parent_id;
    in property <string> variant;
    in property <string> name;
    in property <string> played_at;
    in property <[int]> image;
    in property <int> sort_key;
    callback clicked(int /* id */);

    TouchArea {
        width: parent.width;
        height: parent.height;
        clicked => {
            root.clicked(root.id);
        }
    }

    VerticalBox {
        spacing: 10px;
        Rectangle {
            width: 180px;
            height: 180px;
            border-radius: 90px;
            border-color: Theme.border-color;
            border-width: 1px;
            clip: true;
            Image {
                source: Helper.get_image(image);
                width: 180px;
                height: 180px;
            }
        }

        Text {
            text: name;
            font-size: 16px;
            color: Theme.text-color;
            horizontal-alignment: center;
        }
    }
}

export component TileListView {
    in property <[[UILibraryEntry]]> rows;
    callback entry-clicked(int /* id */);

    width: 100%;
    height: 100%;
    VerticalBox {
        ScrollView {
            VerticalBox {
                for row in rows: HorizontalBox {
                    alignment: center;
                    spacing: 20px;
                    for entry in row: Tile {
                        id: entry.id;
                        parent_id: entry.parent_id;
                        variant: entry.variant;
                        name: entry.name;
                        played_at: entry.played_at;
                        image: entry.image;
                        sort_key: entry.sort_key;
                        clicked => {
                            entry-clicked(entry.id);
                        }
                    }
                }
            }
        }
    }
}
